### ISSUE TITLE
unable to find an inherited method for function 'assays' for signature igraph_layout_modifier

### ISSUE THREAD

**Issue by seandavi** [robertamezquita/OSCABioc2019#4]
When building vignette, I am still seeing:

```
   Quitting from lines 353-354 (OSCABioc2019.Rmd) 
   Error: processing vignette 'OSCABioc2019.Rmd' failed with diagnostics:
   unable to find an inherited method for function 'assays' for signature '"igraph_layout_modifier"'
   --- failed re-building ‘OSCABioc2019.Rmd’
```

**Comment by seandavi** [comment]
Hi, @robertamezquita. Do you think you'll get a chance to look at this in the next few hours? We are trying to finalize the workflows into the AWS Machine Image. Sorry to pester.

**Comment by robertamezquita** [comment]
Yes, I'll be in the office in an hour and a half and will get on this first
thing
